kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: netlabs-app
  namespace: netlabs-app
  labels:
    app: my-app
spec:
  host: example.apps.workshop-netlabs.workshop.netlabs.com.uy
  to:
    kind: Service
    name: my-app
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
